In [546]:
from pymongo import MongoClient
import pandas as pd
from pandas.io.json import json_normalize
import json
from operator import itemgetter


client = MongoClient(host='mongodb://mtl90526:mte40@191.191.5.35:27017/admin?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false')
client

MongoClient(host=['191.191.5.35:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', readpreference='primary', appname='MongoDB Compass', directconnection=True, tls=False)

In [547]:
db = client["SPC_DB_1090"]
db

Database(MongoClient(host=['191.191.5.35:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', readpreference='primary', appname='MongoDB Compass', directconnection=True, tls=False), 'SPC_DB_1090')

In [548]:
mycollection = db["224PB0140"]
mycollection

Collection(Database(MongoClient(host=['191.191.5.35:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', readpreference='primary', appname='MongoDB Compass', directconnection=True, tls=False), 'SPC_DB_1090'), '224PB0140')

In [549]:
one_record = mycollection.find_one()
one_record

{'_id': ObjectId('624a52f510b4586528b51446'),
 'ctrlID': 6,
 'lotNo': '224PB0140',
 'rec_datetime': '2022-04-04 09:07:49.308140',
 'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
  {'param_name': 'temp_id8', 'cur_value': 39.6},
  {'param_name': 'temp_id10', 'cur_value': 39.8},
  {'param_name': 'temp_id12', 'cur_value': 39.2},
  {'param_name': 'temp_id21', 'cur_value': 40.9},
  {'param_name': 'humid_id3', 'cur_value': 28.5},
  {'param_name': 'humid_id8', 'cur_value': 30.0},
  {'param_name': 'humid_id10', 'cur_value': 29.9},
  {'param_name': 'humid_id12', 'cur_value': 31.2},
  {'param_name': 'humid_id21', 'cur_value': 28.7}]}

In [550]:
all_records = mycollection.find() 
all_records

In [551]:
for row in all_records:
    row

In [552]:
all_records = mycollection.find() 
all_records

In [553]:
list_cursor = list(all_records)
list_cursor

[{'_id': ObjectId('624a52f510b4586528b51446'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:07:49.308140',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.7}]},
 {'_id': ObjectId('624a533110b4586528b51460'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:08:49.414904',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.1},
   {'param_name': 'humid_id8', 'cur_value': 29.6},
   {'param_name': 'humid_id10', 'cur_value': 29.6},
   {'param_name': 'humid_id12', 'cur_value': 31.0},
   {'param_name': 'humid_id21', 'cur_value': 28.2}]},
 {'_id': ObjectId('624a536d10b4586528b5147f'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:09:49.317742',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.3},
   {'param_name': 'humid_id8', 'cur_value': 29.7},
   {'param_name': 'humid_id10', 'cur_value': 29.7},
   {'param_name': 'humid_id12', 'cur_value': 31.0},
   {'param_name': 'humid_id21', 'cur_value': 28.4}]},
 {'_id': ObjectId('624a53a910b4586528b5149f'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:10:49.331506',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.6},
   {'param_name': 'humid_id8', 'cur_value': 30.1},
   {'param_name': 'humid_id10', 'cur_value': 30.0},
   {'param_name': 'humid_id12', 'cur_value': 31.4},
   {'param_name': 'humid_id21', 'cur_value': 28.8}]},
 {'_id': ObjectId('624a53e510b4586528b514be'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:11:49.333174',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.6},
   {'param_name': 'humid_id8', 'cur_value': 30.1},
   {'param_name': 'humid_id10', 'cur_value': 30.1},
   {'param_name': 'humid_id12', 'cur_value': 31.4},
   {'param_name': 'humid_id21', 'cur_value': 28.7}]},
 {'_id': ObjectId('624a542110b4586528b514dd'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:12:49.313857',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.6},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 30.0},
   {'param_name': 'humid_id12', 'cur_value': 31.3},
   {'param_name': 'humid_id21', 'cur_value': 28.7}]},
 {'_id': ObjectId('624a545d10b4586528b514fd'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:13:49.226403',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 29.8},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a549910b4586528b5151c'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:14:49.231865',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.4},
   {'param_name': 'humid_id8', 'cur_value': 29.8},
   {'param_name': 'humid_id10', 'cur_value': 29.8},
   {'param_name': 'humid_id12', 'cur_value': 31.1},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a54d510b4586528b5153c'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:15:49.339329',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.7},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 29.8},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a551110b4586528b5155b'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:16:49.262931',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.4},
   {'param_name': 'humid_id8', 'cur_value': 29.8},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.5}]},
 {'_id': ObjectId('624a554d10b4586528b5157b'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:17:49.320788',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.4},
   {'param_name': 'humid_id8', 'cur_value': 29.8},
   {'param_name': 'humid_id10', 'cur_value': 29.8},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.4}]},
 {'_id': ObjectId('624a558910b4586528b5159a'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:18:49.378276',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.3},
   {'param_name': 'humid_id8', 'cur_value': 29.7},
   {'param_name': 'humid_id10', 'cur_value': 29.8},
   {'param_name': 'humid_id12', 'cur_value': 31.1},
   {'param_name': 'humid_id21', 'cur_value': 28.5}]},
 {'_id': ObjectId('624a55c510b4586528b515ba'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:19:49.383564',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 41.0},
   {'param_name': 'humid_id3', 'cur_value': 28.6},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 30.0},
   {'param_name': 'humid_id12', 'cur_value': 31.4},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a560110b4586528b515d9'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:20:49.289858',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a563d10b4586528b515f9'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:21:49.294981',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.6},
   {'param_name': 'humid_id8', 'cur_value': 30.1},
   {'param_name': 'humid_id10', 'cur_value': 30.1},
   {'param_name': 'humid_id12', 'cur_value': 31.4},
   {'param_name': 'humid_id21', 'cur_value': 28.8}]},
 {'_id': ObjectId('624a567910b4586528b51619'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:22:49.609843',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.6},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 30.1},
   {'param_name': 'humid_id12', 'cur_value': 31.4},
   {'param_name': 'humid_id21', 'cur_value': 28.7}]},
 {'_id': ObjectId('624a56b510b4586528b51638'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:23:49.610126',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 30.0},
   {'param_name': 'humid_id12', 'cur_value': 31.3},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a56f110b4586528b51657'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:24:49.078448',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 30.0},
   {'param_name': 'humid_id12', 'cur_value': 31.3},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a572d10b4586528b51677'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:25:49.195886',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.6},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.6},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 30.0},
   {'param_name': 'humid_id12', 'cur_value': 31.3},
   {'param_name': 'humid_id21', 'cur_value': 28.7}]},
 {'_id': ObjectId('624a576910b4586528b51696'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:26:49.191733',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 41.0},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.4},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 29.8},
   {'param_name': 'humid_id12', 'cur_value': 31.1},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a57a510b4586528b516b6'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:27:49.200242',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a57e110b4586528b516d6'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:28:49.203153',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.4},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a581d10b4586528b516f5'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:29:49.203391',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.8},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 30.0},
   {'param_name': 'humid_id12', 'cur_value': 31.3},
   {'param_name': 'humid_id21', 'cur_value': 28.7}]},
 {'_id': ObjectId('624a585910b4586528b51715'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:30:49.134643',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a589510b4586528b51734'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:31:49.234885',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.8},
   {'param_name': 'humid_id3', 'cur_value': 28.3},
   {'param_name': 'humid_id8', 'cur_value': 29.8},
   {'param_name': 'humid_id10', 'cur_value': 29.7},
   {'param_name': 'humid_id12', 'cur_value': 31.1},
   {'param_name': 'humid_id21', 'cur_value': 28.5}]},
 {'_id': ObjectId('624a58d110b4586528b51754'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:32:49.279259',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.8},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a590d10b4586528b51773'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:33:49.218466',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.6},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 30.0},
   {'param_name': 'humid_id12', 'cur_value': 31.4},
   {'param_name': 'humid_id21', 'cur_value': 28.8}]},
 {'_id': ObjectId('624a594910b4586528b51793'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:34:49.344482',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 30.0},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.6}]},
 {'_id': ObjectId('624a598510b4586528b517b2'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:35:49.315182',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.8},
   {'param_name': 'temp_id12', 'cur_value': 39.2},
   {'param_name': 'temp_id21', 'cur_value': 40.9},
   {'param_name': 'humid_id3', 'cur_value': 28.3},
   {'param_name': 'humid_id8', 'cur_value': 29.7},
   {'param_name': 'humid_id10', 'cur_value': 29.6},
   {'param_name': 'humid_id12', 'cur_value': 30.9},
   {'param_name': 'humid_id21', 'cur_value': 28.5}]},
 {'_id': ObjectId('624a59c110b4586528b517d2'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:36:49.466088',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},
   {'param_name': 'temp_id8', 'cur_value': 39.5},
   {'param_name': 'temp_id10', 'cur_value': 39.9},
   {'param_name': 'temp_id12', 'cur_value': 39.3},
   {'param_name': 'temp_id21', 'cur_value': 40.8},
   {'param_name': 'humid_id3', 'cur_value': 28.5},
   {'param_name': 'humid_id8', 'cur_value': 29.9},
   {'param_name': 'humid_id10', 'cur_value': 29.9},
   {'param_name': 'humid_id12', 'cur_value': 31.2},
   {'param_name': 'humid_id21', 'cur_value': 28.7}]},
 {'_id': ObjectId('624a59fd10b4586528b517f1'),
  'ctrlID': 6,
  'lotNo': '224PB0140',
  'rec_datetime': '2022-04-04 09:37:49.371545',
  'unit_data': [{'param_name': 'temp_id3', 'cur_value': 40.9},

In [554]:
df = pd.DataFrame(list_cursor)
df

,_id,ctrlID,lotNo,rec_datetime,unit_data
0,624a52f510b4586528b51446,6,224PB0140,2022-04-04 09:07:49.308140,"[{'param_name': 'temp_id3', 'cur_value': 41.0}..."
1,624a533110b4586528b51460,6,224PB0140,2022-04-04 09:08:49.414904,"[{'param_name': 'temp_id3', 'cur_value': 41.0}..."
2,624a536d10b4586528b5147f,6,224PB0140,2022-04-04 09:09:49.317742,"[{'param_name': 'temp_id3', 'cur_value': 41.0}..."
3,624a53a910b4586528b5149f,6,224PB0140,2022-04-04 09:10:49.331506,"[{'param_name': 'temp_id3', 'cur_value': 41.0}..."
4,624a53e510b4586528b514be,6,224PB0140,2022-04-04 09:11:49.333174,"[{'param_name': 'temp_id3', 'cur_value': 41.0}..."
...,...,...,...,...,...
323,624ac6bdf849d6c052e389a2,6,224PB0140,2022-04-04 17:21:49.865451,"[{'param_name': 'temp_id3', 'cur_value': 40.8}..."
324,624ac6faf849d6c052e389c1,6,224PB0140,2022-04-04 17:22:50.078414,"[{'param_name': 'temp_id3', 'cur_value': 40.8}..."
325,624ac735f849d6c052e389e0,6,224PB0140,2022-04-04 17:23:49.979929,"[{'param_name': 'temp_id3', 'cur_value': 40.8}..."
326,624ac772f849d6c052e389ff,6,224PB0140,2022-04-04 17:24:50.090173,"[{'param_name': 'temp_id3', 'cur_value': 40.8}..."
327,624ac7aef849d6c052e38a1d,6,224PB0140,2022-04-04 17:25:50.094101,"[{'param_name': 'temp_id3', 'cur_value': 40.8}..."

In [555]:
type(df['unit_data'][0])

list

In [556]:
dt = df.explode('unit_data') # ถอด List ออกเพื่อเข้าถึง dict
dt

,_id,ctrlID,lotNo,rec_datetime,unit_data
0,624a52f510b4586528b51446,6,224PB0140,2022-04-04 09:07:49.308140,"{'param_name': 'temp_id3', 'cur_value': 41.0}"
0,624a52f510b4586528b51446,6,224PB0140,2022-04-04 09:07:49.308140,"{'param_name': 'temp_id8', 'cur_value': 39.6}"
0,624a52f510b4586528b51446,6,224PB0140,2022-04-04 09:07:49.308140,"{'param_name': 'temp_id10', 'cur_value': 39.8}"
0,624a52f510b4586528b51446,6,224PB0140,2022-04-04 09:07:49.308140,"{'param_name': 'temp_id12', 'cur_value': 39.2}"
0,624a52f510b4586528b51446,6,224PB0140,2022-04-04 09:07:49.308140,"{'param_name': 'temp_id21', 'cur_value': 40.9}"
...,...,...,...,...,...
327,624ac7aef849d6c052e38a1d,6,224PB0140,2022-04-04 17:25:50.094101,"{'param_name': 'humid_id3', 'cur_value': 28.4}"
327,624ac7aef849d6c052e38a1d,6,224PB0140,2022-04-04 17:25:50.094101,"{'param_name': 'humid_id8', 'cur_value': 29.7}"
327,624ac7aef849d6c052e38a1d,6,224PB0140,2022-04-04 17:25:50.094101,"{'param_name': 'humid_id10', 'cur_value': 29.9}"
327,624ac7aef849d6c052e38a1d,6,224PB0140,2022-04-04 17:25:50.094101,"{'param_name': 'humid_id12', 'cur_value': 31.0}"
327,624ac7aef849d6c052e38a1d,6,224PB0140,2022-04-04 17:25:50.094101,"{'param_name': 'humid_id21', 'cur_value': 28.6}"

In [557]:
js = json_normalize(dt['unit_data'])

C:\Users\mtl91475\AppData\Local\Temp\ipykernel_5640\996814955.py:1: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  js = json_normalize(dt['unit_data'])

In [558]:
# js.transpose()
js

      param_name  cur_value
0       temp_id3       41.0
1       temp_id8       39.6
2      temp_id10       39.8
3      temp_id12       39.2
4      temp_id21       40.9
...          ...        ...
3275   humid_id3       28.4
3276   humid_id8       29.7
3277  humid_id10       29.9
3278  humid_id12       31.0
3279  humid_id21       28.6

[3280 rows x 2 columns]

In [559]:
pivoted = js.pivot(columns='param_name', values='cur_value')\
            .reset_index()
pivoted.columns.name=None
pivoted

,index,humid_id10,humid_id12,humid_id21,humid_id3,humid_id8,temp_id10,temp_id12,temp_id21,temp_id3,temp_id8
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.6
2,2,NaN,NaN,NaN,NaN,NaN,39.8,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,39.2,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3275,3275,NaN,NaN,NaN,28.4,NaN,NaN,NaN,NaN,NaN,NaN
3276,3276,NaN,NaN,NaN,NaN,29.7,NaN,NaN,NaN,NaN,NaN
3277,3277,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3278,3278,NaN,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3279,3279,NaN,NaN,28.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [560]:
tem3 = pd.DataFrame(pivoted['temp_id3'])
tem3

      temp_id3
0         41.0
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
3275       NaN
3276       NaN
3277       NaN
3278       NaN
3279       NaN

[3280 rows x 1 columns]

In [561]:
# dfjs2 = pd.DataFrame(js)
# T2 = dfjs2.transpose()
# T2
tem3.dropna(inplace=True)
tem3.reset_index(inplace=True)
tem3

     index  temp_id3
0        0      41.0
1       10      41.0
2       20      41.0
3       30      41.0
4       40      41.0
..     ...       ...
323   3230      40.8
324   3240      40.8
325   3250      40.8
326   3260      40.8
327   3270      40.8

[328 rows x 2 columns]

In [562]:
tem3.drop("index",axis=1,inplace=True)
tem3

     temp_id3
0        41.0
1        41.0
2        41.0
3        41.0
4        41.0
..        ...
323      40.8
324      40.8
325      40.8
326      40.8
327      40.8

[328 rows x 1 columns]

In [563]:
tem8 = pd.DataFrame(pivoted['temp_id8'])
tem8.dropna(inplace=True)
tem8.reset_index(inplace=True)
tem8.drop("index",axis=1,inplace=True)
tem8

     temp_id8
0        39.6
1        39.6
2        39.6
3        39.6
4        39.6
..        ...
323      39.4
324      39.4
325      39.4
326      39.5
327      39.5

[328 rows x 1 columns]

In [564]:
tem10 = pd.DataFrame(pivoted['temp_id10'])
tem10.dropna(inplace=True)
tem10.reset_index(inplace=True)
tem10.drop("index",axis=1,inplace=True)
tem10

     temp_id10
0         39.8
1         39.9
2         39.9
3         39.8
4         39.9
..         ...
323       39.7
324       39.7
325       39.7
326       39.7
327       39.7

[328 rows x 1 columns]

In [565]:
tem12 = pd.DataFrame(pivoted['temp_id12'])
tem12.dropna(inplace=True)
tem12.reset_index(inplace=True)
tem12.drop("index",axis=1,inplace=True)
tem12

     temp_id12
0         39.2
1         39.2
2         39.3
3         39.3
4         39.3
..         ...
323       39.2
324       39.2
325       39.2
326       39.2
327       39.2

[328 rows x 1 columns]

In [566]:
tem21 = pd.DataFrame(pivoted['temp_id21'])
tem21.dropna(inplace=True)
tem21.reset_index(inplace=True)
tem21.drop("index",axis=1,inplace=True)
tem21

     temp_id21
0         40.9
1         40.9
2         40.9
3         40.9
4         40.9
..         ...
323       40.7
324       40.7
325       40.7
326       40.7
327       40.7

[328 rows x 1 columns]

In [567]:
hum3 = pd.DataFrame(pivoted['humid_id3'])
hum3.dropna(inplace=True)
hum3.reset_index(inplace=True)
hum3.drop("index",axis=1,inplace=True)
hum3

     humid_id3
0         28.5
1         28.1
2         28.3
3         28.6
4         28.6
..         ...
323       28.2
324       28.3
325       28.4
326       28.4
327       28.4

[328 rows x 1 columns]

In [568]:
hum8 = pd.DataFrame(pivoted['humid_id8'])
hum8.dropna(inplace=True)
hum8.reset_index(inplace=True)
hum8.drop("index",axis=1,inplace=True)
hum8

     humid_id8
0         30.0
1         29.6
2         29.7
3         30.1
4         30.1
..         ...
323       29.7
324       29.7
325       29.7
326       29.7
327       29.7

[328 rows x 1 columns]

In [569]:
hum10 = pd.DataFrame(pivoted['humid_id10'])
hum10.dropna(inplace=True)
hum10.reset_index(inplace=True)
hum10.drop("index",axis=1,inplace=True)
hum10

     humid_id10
0          29.9
1          29.6
2          29.7
3          30.0
4          30.1
..          ...
323        29.7
324        29.8
325        29.8
326        29.8
327        29.9

[328 rows x 1 columns]

In [570]:
hum12 = pd.DataFrame(pivoted['humid_id12'])
hum12.dropna(inplace=True)
hum12.reset_index(inplace=True)
hum12.drop("index",axis=1,inplace=True)
hum12

     humid_id12
0          31.2
1          31.0
2          31.0
3          31.4
4          31.4
..          ...
323        31.0
324        31.0
325        31.0
326        30.9
327        31.0

[328 rows x 1 columns]

In [571]:
hum21 = pd.DataFrame(pivoted['humid_id21'])
hum21.dropna(inplace=True)
hum21.reset_index(inplace=True)
hum21.drop("index",axis=1,inplace=True)
hum21

     humid_id21
0          28.7
1          28.2
2          28.4
3          28.8
4          28.7
..          ...
323        28.5
324        28.5
325        28.6
326        28.6
327        28.6

[328 rows x 1 columns]

In [572]:
cc2 = pd.concat([df, tem3,hum3,tem8,hum8,tem10,hum10,tem12,hum12,tem21,hum21],axis=1)
cc2.set_index(['rec_datetime'],inplace=True)
cc2.drop("unit_data",axis=1,inplace=True)
cc2

,_id,ctrlID,lotNo,temp_id3,humid_id3,temp_id8,humid_id8,temp_id10,humid_id10,temp_id12,humid_id12,temp_id21,humid_id21
rec_datetime,,,,,,,,,,,,,
2022-04-04 09:07:49.308140,624a52f510b4586528b51446,6,224PB0140,41.0,28.5,39.6,30.0,39.8,29.9,39.2,31.2,40.9,28.7
2022-04-04 09:08:49.414904,624a533110b4586528b51460,6,224PB0140,41.0,28.1,39.6,29.6,39.9,29.6,39.2,31.0,40.9,28.2
2022-04-04 09:09:49.317742,624a536d10b4586528b5147f,6,224PB0140,41.0,28.3,39.6,29.7,39.9,29.7,39.3,31.0,40.9,28.4
2022-04-04 09:10:49.331506,624a53a910b4586528b5149f,6,224PB0140,41.0,28.6,39.6,30.1,39.8,30.0,39.3,31.4,40.9,28.8
2022-04-04 09:11:49.333174,624a53e510b4586528b514be,6,224PB0140,41.0,28.6,39.6,30.1,39.9,30.1,39.3,31.4,40.9,28.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-04-04 17:21:49.865451,624ac6bdf849d6c052e389a2,6,224PB0140,40.8,28.2,39.4,29.7,39.7,29.7,39.2,31.0,40.7,28.5
2022-04-04 17:22:50.078414,624ac6faf849d6c052e389c1,6,224PB0140,40.8,28.3,39.4,29.7,39.7,29.8,39.2,31.0,40.7,28.5
2022-04-04 17:23:49.979929,624ac735f849d6c052e389e0,6,224PB0140,40.8,28.4,39.4,29.7,39.7,29.8,39.2,31.0,40.7,28.6
2022-04-04 17:24:50.090173,624ac772f849d6c052e389ff,6,224PB0140,40.8,28.4,39.5,29.7,39.7,29.8,39.2,30.9,40.7,28.6
2022-04-04 17:25:50.094101,624ac7aef849d6c052e38a1d,6,224PB0140,40.8,28.4,39.5,29.7,39.7,29.9,39.2,31.0,40.7,28.6

In [573]:
cc2.to_csv('224PB0140.csv')